#!/usr/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Manjaro" Linux --class manjaro --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-aff663b0-751b-4c8b-84d6-fcf5b7ac9690' {
	set root='hd1,msdos1'
	linux   /boot/vmlinuz-4.19-x86_64 root=UUID=aff663b0-751b-4c8b-84d6-fcf5b7ac9690 rw  quiet rd.udev.log-priority=3
        initrd  /boot/intel-ucode.img /boot/initramfs-4.19-x86_64.img
}
